params:
  "objective": "binary"
  "metric": "binary_logloss"
  "random_state": 100
  "verbosity": -1
  "feature_fraction": 0.8
  "bagging_fraction": 0.8
  "learning_rate": 0.01
  "bagging_freq": 1
features:
  - horse_id
  - jockey_id
  - trainer_id
  - umaban
  - wakuban
  - tansho_odds
  - popularity
  - impost
  - sex
  - age
  - weight
  - weight_diff
  - race_type
  - around
  - course_len
  - weather
  - ground_state
  - race_class
  - place
  - rank_3races
  - prize_3races
  - rank_5races
  - prize_5races
  - rank_10races
  - prize_10races
  - rank_1000races
  - prize_1000races
  - rank_mean_2races_relative
  - rank_median_2races_relative
  - rank_max_2races_relative
  - rank_min_2races_relative
  - prize_mean_2races_relative
  - prize_median_2races_relative
  - prize_max_2races_relative
  - prize_min_2races_relative
  - rank_diff_mean_2races_relative
  - rank_diff_median_2races_relative
  - rank_diff_max_2races_relative
  - rank_diff_min_2races_relative
  - race_class_mean_2races_relative
  - race_class_median_2races_relative
  - race_class_max_2races_relative
  - race_class_min_2races_relative
  - rank_mean_3races_relative
  - rank_median_3races_relative
  - rank_max_3races_relative
  - rank_min_3races_relative
  - prize_mean_3races_relative
  - prize_median_3races_relative
  - prize_max_3races_relative
  - prize_min_3races_relative
  - rank_diff_mean_3races_relative
  - rank_diff_median_3races_relative
  - rank_diff_max_3races_relative
  - rank_diff_min_3races_relative
  - race_class_mean_3races_relative
  - race_class_median_3races_relative
  - race_class_max_3races_relative
  - race_class_min_3races_relative
  - rank_mean_5races_relative
  - rank_median_5races_relative
  - rank_max_5races_relative
  - rank_min_5races_relative
  - prize_mean_5races_relative
  - prize_median_5races_relative
  - prize_max_5races_relative
  - prize_min_5races_relative
  - rank_diff_mean_5races_relative
  - rank_diff_median_5races_relative
  - rank_diff_max_5races_relative
  - rank_diff_min_5races_relative
  - race_class_mean_5races_relative
  - race_class_median_5races_relative
  - race_class_max_5races_relative
  - race_class_min_5races_relative
  - rank_mean_10races_relative
  - rank_median_10races_relative
  - rank_max_10races_relative
  - rank_min_10races_relative
  - prize_mean_10races_relative
  - prize_median_10races_relative
  - prize_max_10races_relative
  - prize_min_10races_relative
  - rank_diff_mean_10races_relative
  - rank_diff_median_10races_relative
  - rank_diff_max_10races_relative
  - rank_diff_min_10races_relative
  - race_class_mean_10races_relative
  - race_class_median_10races_relative
  - race_class_max_10races_relative
  - race_class_min_10races_relative
  - rank_mean_1000races_relative
  - rank_median_1000races_relative
  - rank_max_1000races_relative
  - rank_min_1000races_relative
  - prize_mean_1000races_relative
  - prize_median_1000races_relative
  - prize_max_1000races_relative
  - prize_min_1000races_relative
  - rank_diff_mean_1000races_relative
  - rank_diff_median_1000races_relative
  - rank_diff_max_1000races_relative
  - rank_diff_min_1000races_relative
  - race_class_mean_1000races_relative
  - race_class_median_1000races_relative
  - race_class_max_1000races_relative
  - race_class_min_1000races_relative
  
  - jockey_rank_relative
  - jockey_n_races_relative
  - jockey_n_races_graded_relative
  - jockey_winrate_graded_relative
  - jockey_n_races_special_relative
  - jockey_winrate_special_relative
  - jockey_n_races_ordinal_relative
  - jockey_winrate_ordinal_relative
  - jockey_n_races_turf_relative
  - jockey_winrate_turf_relative
  - jockey_n_races_dirt_relative
  - jockey_winrate_dirt_relative
  - jockey_winrate_relative
  - jockey_placerate_relative
  - jockey_showrate_relative
  - jockey_prize_relative
  - trainer_rank_relative
  - trainer_n_races_relative
  - trainer_n_races_graded_relative
  - trainer_winrate_graded_relative
  - trainer_n_races_special_relative
  - trainer_winrate_special_relative
  - trainer_n_races_ordinal_relative
  - trainer_winrate_ordinal_relative
  - trainer_n_races_turf_relative
  - trainer_winrate_turf_relative
  - trainer_n_races_dirt_relative
  - trainer_winrate_dirt_relative
  - trainer_winrate_relative
  - trainer_placerate_relative
  - trainer_showrate_relative
  - trainer_prize_relative

  
  - rank_mean_1races_per_course_len_relative
  - rank_min_1races_per_course_len_relative
  - prize_mean_1races_per_course_len_relative
  - prize_min_1races_per_course_len_relative
  - rank_diff_mean_1races_per_course_len_relative
  - rank_diff_min_1races_per_course_len_relative
  - time_mean_1races_per_course_len_relative
  - time_min_1races_per_course_len_relative
  - win_mean_1races_per_course_len_relative
  - show_mean_1races_per_course_len_relative
  - show_min_1races_per_course_len_relative
  - rank_mean_2races_per_course_len_relative
  - rank_min_2races_per_course_len_relative
  - prize_mean_2races_per_course_len_relative
  - prize_min_2races_per_course_len_relative
  - rank_diff_mean_2races_per_course_len_relative
  - rank_diff_min_2races_per_course_len_relative
  - time_mean_2races_per_course_len_relative
  - time_min_2races_per_course_len_relative
  - win_mean_2races_per_course_len_relative
  - show_mean_2races_per_course_len_relative
  - show_min_2races_per_course_len_relative
  - rank_mean_3races_per_course_len_relative
  - rank_min_3races_per_course_len_relative
  - prize_mean_3races_per_course_len_relative
  - prize_min_3races_per_course_len_relative
  - rank_diff_mean_3races_per_course_len_relative
  - rank_diff_min_3races_per_course_len_relative
  - time_mean_3races_per_course_len_relative
  - time_min_3races_per_course_len_relative
  - win_mean_3races_per_course_len_relative
  - show_mean_3races_per_course_len_relative
  - show_min_3races_per_course_len_relative
  - rank_mean_5races_per_course_len_relative
  - rank_min_5races_per_course_len_relative
  - prize_mean_5races_per_course_len_relative
  - prize_min_5races_per_course_len_relative
  - rank_diff_mean_5races_per_course_len_relative
  - rank_diff_min_5races_per_course_len_relative
  - time_mean_5races_per_course_len_relative
  - time_min_5races_per_course_len_relative
  - win_mean_5races_per_course_len_relative
  - show_mean_5races_per_course_len_relative
  - show_min_5races_per_course_len_relative
  - rank_mean_10races_per_course_len_relative
  - rank_min_10races_per_course_len_relative
  - prize_mean_10races_per_course_len_relative
  - prize_min_10races_per_course_len_relative
  - rank_diff_mean_10races_per_course_len_relative
  - rank_diff_min_10races_per_course_len_relative
  - time_mean_10races_per_course_len_relative
  - time_min_10races_per_course_len_relative
  - win_mean_10races_per_course_len_relative
  - show_mean_10races_per_course_len_relative
  - show_min_10races_per_course_len_relative
  - rank_mean_20races_per_course_len_relative
  - rank_min_20races_per_course_len_relative
  - prize_mean_20races_per_course_len_relative
  - prize_min_20races_per_course_len_relative
  - rank_diff_mean_20races_per_course_len_relative
  - rank_diff_min_20races_per_course_len_relative
  - time_mean_20races_per_course_len_relative
  - time_min_20races_per_course_len_relative
  - win_mean_20races_per_course_len_relative
  - show_mean_20races_per_course_len_relative
  - show_min_20races_per_course_len_relative
  - rank_mean_1races_per_race_class_relative
  - rank_max_1races_per_race_class_relative
  - rank_min_1races_per_race_class_relative
  - prize_mean_1races_per_race_class_relative
  - prize_max_1races_per_race_class_relative
  - prize_min_1races_per_race_class_relative
  - rank_diff_mean_1races_per_race_class_relative
  - rank_diff_max_1races_per_race_class_relative
  - rank_diff_min_1races_per_race_class_relative
  - win_mean_1races_per_race_class_relative
  - win_max_1races_per_race_class_relative
  - show_mean_1races_per_race_class_relative
  - show_max_1races_per_race_class_relative
  - show_min_1races_per_race_class_relative
  - rank_mean_2races_per_race_class_relative
  - rank_max_2races_per_race_class_relative
  - rank_min_2races_per_race_class_relative
  - prize_mean_2races_per_race_class_relative
  - prize_max_2races_per_race_class_relative
  - prize_min_2races_per_race_class_relative
  - rank_diff_mean_2races_per_race_class_relative
  - rank_diff_max_2races_per_race_class_relative
  - rank_diff_min_2races_per_race_class_relative
  - win_mean_2races_per_race_class_relative
  - win_max_2races_per_race_class_relative
  - show_mean_2races_per_race_class_relative
  - show_max_2races_per_race_class_relative
  - show_min_2races_per_race_class_relative
  - rank_mean_3races_per_race_class_relative
  - rank_max_3races_per_race_class_relative
  - rank_min_3races_per_race_class_relative
  - prize_mean_3races_per_race_class_relative
  - prize_max_3races_per_race_class_relative
  - prize_min_3races_per_race_class_relative
  - rank_diff_mean_3races_per_race_class_relative
  - rank_diff_max_3races_per_race_class_relative
  - rank_diff_min_3races_per_race_class_relative
  - win_mean_3races_per_race_class_relative
  - win_max_3races_per_race_class_relative
  - show_mean_3races_per_race_class_relative
  - show_max_3races_per_race_class_relative
  - show_min_3races_per_race_class_relative
  - rank_mean_5races_per_race_class_relative
  - rank_max_5races_per_race_class_relative
  - rank_min_5races_per_race_class_relative
  - prize_mean_5races_per_race_class_relative
  - prize_max_5races_per_race_class_relative
  - prize_min_5races_per_race_class_relative
  - rank_diff_mean_5races_per_race_class_relative
  - rank_diff_max_5races_per_race_class_relative
  - rank_diff_min_5races_per_race_class_relative
  - win_mean_5races_per_race_class_relative
  - win_max_5races_per_race_class_relative
  - show_mean_5races_per_race_class_relative
  - show_max_5races_per_race_class_relative
  - show_min_5races_per_race_class_relative
  - rank_mean_10races_per_race_class_relative
  - rank_max_10races_per_race_class_relative
  - rank_min_10races_per_race_class_relative
  - prize_mean_10races_per_race_class_relative
  - prize_max_10races_per_race_class_relative
  - prize_min_10races_per_race_class_relative
  - rank_diff_mean_10races_per_race_class_relative
  - rank_diff_max_10races_per_race_class_relative
  - rank_diff_min_10races_per_race_class_relative
  - win_mean_10races_per_race_class_relative
  - win_max_10races_per_race_class_relative
  - show_mean_10races_per_race_class_relative
  - show_max_10races_per_race_class_relative
  - show_min_10races_per_race_class_relative
  - rank_mean_20races_per_race_class_relative
  - rank_max_20races_per_race_class_relative
  - rank_min_20races_per_race_class_relative
  - prize_mean_20races_per_race_class_relative
  - prize_max_20races_per_race_class_relative
  - prize_min_20races_per_race_class_relative
  - rank_diff_mean_20races_per_race_class_relative
  - rank_diff_max_20races_per_race_class_relative
  - rank_diff_min_20races_per_race_class_relative
  - win_mean_20races_per_race_class_relative
  - win_max_20races_per_race_class_relative
  - show_mean_20races_per_race_class_relative
  - show_max_20races_per_race_class_relative
  - show_min_20races_per_race_class_relative
  - rank_mean_1races_per_ground_state_race_type_relative
  - rank_max_1races_per_ground_state_race_type_relative
  - rank_min_1races_per_ground_state_race_type_relative
  - prize_mean_1races_per_ground_state_race_type_relative
  - prize_max_1races_per_ground_state_race_type_relative
  - prize_min_1races_per_ground_state_race_type_relative
  - rank_diff_mean_1races_per_ground_state_race_type_relative
  - rank_diff_max_1races_per_ground_state_race_type_relative
  - rank_diff_min_1races_per_ground_state_race_type_relative
  - win_mean_1races_per_ground_state_race_type_relative
  - win_max_1races_per_ground_state_race_type_relative
  - show_mean_1races_per_ground_state_race_type_relative
  - show_max_1races_per_ground_state_race_type_relative
  - show_min_1races_per_ground_state_race_type_relative
  - rank_mean_2races_per_ground_state_race_type_relative
  - rank_max_2races_per_ground_state_race_type_relative
  - rank_min_2races_per_ground_state_race_type_relative
  - prize_mean_2races_per_ground_state_race_type_relative
  - prize_max_2races_per_ground_state_race_type_relative
  - prize_min_2races_per_ground_state_race_type_relative
  - rank_diff_mean_2races_per_ground_state_race_type_relative
  - rank_diff_max_2races_per_ground_state_race_type_relative
  - rank_diff_min_2races_per_ground_state_race_type_relative
  - win_mean_2races_per_ground_state_race_type_relative
  - win_max_2races_per_ground_state_race_type_relative
  - show_mean_2races_per_ground_state_race_type_relative
  - show_max_2races_per_ground_state_race_type_relative
  - show_min_2races_per_ground_state_race_type_relative
  - rank_mean_3races_per_ground_state_race_type_relative
  - rank_max_3races_per_ground_state_race_type_relative
  - rank_min_3races_per_ground_state_race_type_relative
  - prize_mean_3races_per_ground_state_race_type_relative
  - prize_max_3races_per_ground_state_race_type_relative
  - prize_min_3races_per_ground_state_race_type_relative
  - rank_diff_mean_3races_per_ground_state_race_type_relative
  - rank_diff_max_3races_per_ground_state_race_type_relative
  - rank_diff_min_3races_per_ground_state_race_type_relative
  - win_mean_3races_per_ground_state_race_type_relative
  - win_max_3races_per_ground_state_race_type_relative
  - show_mean_3races_per_ground_state_race_type_relative
  - show_max_3races_per_ground_state_race_type_relative
  - show_min_3races_per_ground_state_race_type_relative
  - rank_mean_5races_per_ground_state_race_type_relative
  - rank_max_5races_per_ground_state_race_type_relative
  - rank_min_5races_per_ground_state_race_type_relative
  - prize_mean_5races_per_ground_state_race_type_relative
  - prize_max_5races_per_ground_state_race_type_relative
  - prize_min_5races_per_ground_state_race_type_relative
  - rank_diff_mean_5races_per_ground_state_race_type_relative
  - rank_diff_max_5races_per_ground_state_race_type_relative
  - rank_diff_min_5races_per_ground_state_race_type_relative
  - win_mean_5races_per_ground_state_race_type_relative
  - win_max_5races_per_ground_state_race_type_relative
  - show_mean_5races_per_ground_state_race_type_relative
  - show_max_5races_per_ground_state_race_type_relative
  - show_min_5races_per_ground_state_race_type_relative
  - rank_mean_10races_per_ground_state_race_type_relative
  - rank_max_10races_per_ground_state_race_type_relative
  - rank_min_10races_per_ground_state_race_type_relative
  - prize_mean_10races_per_ground_state_race_type_relative
  - prize_max_10races_per_ground_state_race_type_relative
  - prize_min_10races_per_ground_state_race_type_relative
  - rank_diff_mean_10races_per_ground_state_race_type_relative
  - rank_diff_max_10races_per_ground_state_race_type_relative
  - rank_diff_min_10races_per_ground_state_race_type_relative
  - win_mean_10races_per_ground_state_race_type_relative
  - win_max_10races_per_ground_state_race_type_relative
  - show_mean_10races_per_ground_state_race_type_relative
  - show_max_10races_per_ground_state_race_type_relative
  - show_min_10races_per_ground_state_race_type_relative
  - rank_mean_20races_per_ground_state_race_type_relative
  - rank_max_20races_per_ground_state_race_type_relative
  - rank_min_20races_per_ground_state_race_type_relative
  - prize_mean_20races_per_ground_state_race_type_relative
  - prize_max_20races_per_ground_state_race_type_relative
  - prize_min_20races_per_ground_state_race_type_relative
  - rank_diff_mean_20races_per_ground_state_race_type_relative
  - rank_diff_max_20races_per_ground_state_race_type_relative
  - rank_diff_min_20races_per_ground_state_race_type_relative
  - win_mean_20races_per_ground_state_race_type_relative
  - win_max_20races_per_ground_state_race_type_relative
  - show_mean_20races_per_ground_state_race_type_relative
  - show_max_20races_per_ground_state_race_type_relative
  - show_min_20races_per_ground_state_race_type_relative
  
  - sire_n_races_relative
  - sire_n_wins_relative
  - sire_winrate_relative
  - sire_course_len_diff_relative
  
  - rank_mean_1races_per_race_type_relative
  - rank_max_1races_per_race_type_relative
  - rank_min_1races_per_race_type_relative
  - prize_mean_1races_per_race_type_relative
  - prize_max_1races_per_race_type_relative
  - prize_min_1races_per_race_type_relative
  - rank_diff_mean_1races_per_race_type_relative
  - rank_diff_max_1races_per_race_type_relative
  - rank_diff_min_1races_per_race_type_relative
  - win_mean_1races_per_race_type_relative
  - win_max_1races_per_race_type_relative
  - show_mean_1races_per_race_type_relative
  - show_max_1races_per_race_type_relative
  - show_min_1races_per_race_type_relative
  - rank_mean_2races_per_race_type_relative
  - rank_max_2races_per_race_type_relative
  - rank_min_2races_per_race_type_relative
  - prize_mean_2races_per_race_type_relative
  - prize_max_2races_per_race_type_relative
  - prize_min_2races_per_race_type_relative
  - rank_diff_mean_2races_per_race_type_relative
  - rank_diff_max_2races_per_race_type_relative
  - rank_diff_min_2races_per_race_type_relative
  - win_mean_2races_per_race_type_relative
  - win_max_2races_per_race_type_relative
  - show_mean_2races_per_race_type_relative
  - show_max_2races_per_race_type_relative
  - show_min_2races_per_race_type_relative
  - rank_mean_3races_per_race_type_relative
  - rank_max_3races_per_race_type_relative
  - rank_min_3races_per_race_type_relative
  - prize_mean_3races_per_race_type_relative
  - prize_max_3races_per_race_type_relative
  - prize_min_3races_per_race_type_relative
  - rank_diff_mean_3races_per_race_type_relative
  - rank_diff_max_3races_per_race_type_relative
  - rank_diff_min_3races_per_race_type_relative
  - win_mean_3races_per_race_type_relative
  - win_max_3races_per_race_type_relative
  - show_mean_3races_per_race_type_relative
  - show_max_3races_per_race_type_relative
  - show_min_3races_per_race_type_relative
  - rank_mean_5races_per_race_type_relative
  - rank_max_5races_per_race_type_relative
  - rank_min_5races_per_race_type_relative
  - prize_mean_5races_per_race_type_relative
  - prize_max_5races_per_race_type_relative
  - prize_min_5races_per_race_type_relative
  - rank_diff_mean_5races_per_race_type_relative
  - rank_diff_max_5races_per_race_type_relative
  - rank_diff_min_5races_per_race_type_relative
  - win_mean_5races_per_race_type_relative
  - win_max_5races_per_race_type_relative
  - show_mean_5races_per_race_type_relative
  - show_max_5races_per_race_type_relative
  - show_min_5races_per_race_type_relative
  - rank_mean_10races_per_race_type_relative
  - rank_max_10races_per_race_type_relative
  - rank_min_10races_per_race_type_relative
  - prize_mean_10races_per_race_type_relative
  - prize_max_10races_per_race_type_relative
  - prize_min_10races_per_race_type_relative
  - rank_diff_mean_10races_per_race_type_relative
  - rank_diff_max_10races_per_race_type_relative
  - rank_diff_min_10races_per_race_type_relative
  - win_mean_10races_per_race_type_relative
  - win_max_10races_per_race_type_relative
  - show_mean_10races_per_race_type_relative
  - show_max_10races_per_race_type_relative
  - show_min_10races_per_race_type_relative
  - rank_mean_20races_per_race_type_relative
  - rank_max_20races_per_race_type_relative
  - rank_min_20races_per_race_type_relative
  - prize_mean_20races_per_race_type_relative
  - prize_max_20races_per_race_type_relative
  - prize_min_20races_per_race_type_relative
  - rank_diff_mean_20races_per_race_type_relative
  - rank_diff_max_20races_per_race_type_relative
  - rank_diff_min_20races_per_race_type_relative
  - win_mean_20races_per_race_type_relative
  - win_max_20races_per_race_type_relative
  - show_mean_20races_per_race_type_relative
  - show_max_20races_per_race_type_relative
  - show_min_20races_per_race_type_relative